######################################################
# Serveur de déploiement 
# 
######################################################
# reference docker hub
# jenkins/jenkins:lts-jdk11 => https://hub.docker.com/layers/jenkins/jenkins/lts-jdk11/images/sha256-8f7043722b3bb576fde60fa4ab59465a4b77e677c92774514897301ab77825a3?context=explore
# Version du moteur docker
version: '3.8'

services:
    ######################################################
    # Jenkins 
    jenkins:
        image: jenkins/docker
        container_name: jenkins
        build:
            context: .
        user: jenkins
        restart: always
        ports:
            -   ${JENKINS_HTTP}           # http_port  le client jenkins
            -   ${JENKINS_AGENT}          # agent_port  master / slave communication

        volumes:
            -  $PWD/jenkins_home:/var/jenkins_home          # le dossier de jenkins
            - /var/run/docker.sock:/var/run/docker.sock     # accès au démon Docker

        environment:
            - JENKINS_OPTS="--prefix=/jenkins"


# l'utilisateur qui excute le docker compose doit avoir les
# droit en écriture pour la création des volumes au lance du conteneur

# docker-compose up -d