######################################################
# Serveur de déploiement 
# 
######################################################

# Version du moteur docker
version: '3.8'

services:
    ######################################################
    # Jenkins 
    jenkins:
        image: jenkins/jenkins:lts-jdk11
        container_name: jenkins
        restart: always
        ports:
            -   ${JENKINS_HTTP}           # http_port  le client jenkins
            -   ${JENKINS_AGENT}          # agent_port  master / slave communication

        volumes:
            -  ./jenkins_home:/var/jenkins_home:rw           # Data persistance

        environment:
            - JENKINS_OPTS="--prefix=/jenkins"
